# Generated by Django 2.2.5 on 2019-09-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('class_short_form', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentShiftInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='address',
            field=models.CharField(default='Pirojpur', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='fathers_name',
            field=models.CharField(default='Mr. S', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='roll',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_section', models.CharField(max_length=100)),
                ('std_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentClassInfo')),
                ('std_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentShiftInfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentInfo')),
            ],
        ),
    ]
