# Generated by Django 2.2.5 on 2019-09-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190923_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetailinfo',
            name='std_session',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
