# Generated by Django 2.2.5 on 2019-09-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentdetailinfo_std_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='address',
            field=models.TextField(max_length=200),
        ),
    ]
